### ISSUE TITLE
Conversion Prophesee dat format to h5

### ISSUE THREAD

**Issue by BoogaardR** [uzh-rpg/e2calib#19]
Hi,
I have a question about the conversion of .dat to h5. Can i use metavision 2.3.1 for this? Since 2.2 is not available anymore.

Thanks in advance.

**Comment by Manasi94** [comment]
The script should be compatible with 2.3 version as well.
For metavision version>2.0, you can also directly convert from .raw file to h5, without converting to ".dat" format.

**Comment by BoogaardR** [comment]
Hi,

If i do so, i am getting errors. Do you know how to fix this?
Rik

**Comment by Manasi94** [comment]
Can you elaborate on what error you get?

**Comment by BoogaardR** [comment]
I include a photo of it in the appendix.

**Comment by magehrig** [comment]
Please post your error message here in a code block so others who have the same problem can find the issue
